import { buildRoute, sanitizeSegments } from "../../domain/route/route-builder.js";
import { WORKOUT_MODES } from "../../domain/workout/workout-mode.js";
import { TRAINER_CONTROL_MODES } from "../../domain/workout/trainer-command.js";
import { createDefaultCustomWorkoutTarget } from "../../domain/workout/custom-workout-target.js";
import { createInitialSensorSamplingState } from "../realtime/sensor-sampling.js";
import { clamp, normalizeText } from "../../shared/utils/common.js";

export const defaultRouteSegments = [
    { name: "平路 0%", distanceKm: 0.1, gradePercent: 0 },
    { name: "爬坡 1%", distanceKm: 0.1, gradePercent: 1 },
    { name: "爬坡 2%", distanceKm: 0.1, gradePercent: 2 },
    { name: "爬坡 3%", distanceKm: 0.1, gradePercent: 3 },
    { name: "爬坡 4%", distanceKm: 0.1, gradePercent: 4 },
    { name: "爬坡 5%", distanceKm: 0.1, gradePercent: 5 },
    { name: "缓降 4%", distanceKm: 0.1, gradePercent: 4 },
    { name: "缓降 3%", distanceKm: 0.1, gradePercent: 3 },
    { name: "缓降 2%", distanceKm: 0.1, gradePercent: 2 },
    { name: "缓降 1%", distanceKm: 0.1, gradePercent: 1 },
    { name: "平路 0%", distanceKm: 0.1, gradePercent: 0 },
    { name: "下坡 -1%", distanceKm: 0.1, gradePercent: -1 }
];

export const defaultSettings = {
    power: 220,
    mass: 78,
    ftp: 250,
    restingHr: 58,
    maxHr: 182,
    cda: 0.32,
    crr: 0.004,
    windSpeed: 0
};

export const defaultExportMetadata = {
    activityName: "Rider Tracker Virtual Ride",
    fitDescription: "Virtual ride generated by Rider Tracker.",
    repositoryUrl: "https://github.com/jsdylhw/rider-tracker",
    uploadEndpoint: "",
    markVirtualActivity: true
};

export const STREET_VIEW_UPDATE_INTERVAL_MS = 3000;

export function createInitialState(session) {
    const routeSegments = sanitizeSegments(defaultRouteSegments);
    const route = buildRoute(routeSegments);

    return {
        uiMode: "home",
        routeSegments,
        route,
        settings: { ...defaultSettings },
        workout: createInitialWorkoutState(),
        session,
        liveRide: createInitialLiveRideState(),
        ble: createInitialBleState(),
        exportMetadata: {
            ...defaultExportMetadata,
            ...(session?.exportMetadata ?? {})
        },
        hasPersistedSession: Boolean(session),
        pipConfig: {
            hr: true,
            power: true,
            time: true,
            np: true
        },
        statusText: "请先设置路线与模拟参数。"
    };
}

export function sanitizeSettings(settings) {
    return {
        power: clamp(settings.power, 80, 600, defaultSettings.power),
        mass: clamp(settings.mass, 40, 150, defaultSettings.mass),
        ftp: clamp(settings.ftp, 120, 450, defaultSettings.ftp),
        restingHr: clamp(settings.restingHr, 40, 100, defaultSettings.restingHr),
        maxHr: clamp(settings.maxHr, 120, 220, defaultSettings.maxHr),
        cda: clamp(settings.cda, 0.2, 0.8, defaultSettings.cda),
        crr: clamp(settings.crr, 0.001, 0.02, defaultSettings.crr),
        windSpeed: clamp(settings.windSpeed, -10, 10, defaultSettings.windSpeed)
    };
}

export function sanitizeExportMetadata(exportMetadata) {
    return {
        activityName: normalizeText(exportMetadata.activityName, defaultExportMetadata.activityName, 48),
        fitDescription: normalizeText(exportMetadata.fitDescription, defaultExportMetadata.fitDescription, 180),
        repositoryUrl: normalizeText(exportMetadata.repositoryUrl, defaultExportMetadata.repositoryUrl, 120),
        uploadEndpoint: normalizeText(exportMetadata.uploadEndpoint, defaultExportMetadata.uploadEndpoint, 300),
        markVirtualActivity: normalizeBoolean(exportMetadata.markVirtualActivity, defaultExportMetadata.markVirtualActivity)
    };
}

function normalizeBoolean(value, fallback) {
    if (typeof value === "boolean") {
        return value;
    }
    if (typeof value === "string") {
        const text = value.trim().toLowerCase();
        if (text === "true") return true;
        if (text === "false") return false;
    }
    return fallback;
}

function createInitialLiveRideState() {
    return {
        isActive: false,
        canStart: false,
        dashboardOpen: false,
        snapshot: null,
        session: null,
        trainerControlMode: null,
        customWorkoutTargetPlan: null,
        commandSequence: 0,
        commandDispatch: {
            lastSentAtMs: null,
            lastAttemptedAtMs: null,
            lastSentControlMode: null,
            lastSentGradePercent: 0,
            lastSentPowerWatts: null,
            lastSentResistanceLevel: null,
            inFlightCommandKey: null
        },
        startedAt: null,
        lastCompletedAt: null,
        statusMeta: "连接功率计后即可开始骑行。"
    };
}

function createInitialWorkoutState() {
    return {
        mode: WORKOUT_MODES.GRADE_SIM,
        gradeSimulation: {
            difficultyPercent: 100,
            lookaheadMeters: 120,
            maxUphillPercent: 20,
            maxDownhillPercent: 0,
            smoothingFactor: 0.7
        },
        erg: {
            confirmationRequired: false
        },
        customWorkoutTarget: createDefaultCustomWorkoutTarget(),
        runtime: {
            available: false,
            trainerControlMode: TRAINER_CONTROL_MODES.SIM,
            currentGradePercent: 0,
            lookaheadGradePercent: 0,
            targetTrainerGradePercent: 0,
            targetErgPowerWatts: null,
            targetResistanceLevel: 35,
            ergConfirmationRequired: false,
            customWorkoutTargetEnabled: false,
            customWorkoutTargetSteps: [],
            customWorkoutTargetTotalSeconds: 0,
            customWorkoutTargetActive: false,
            customWorkoutTargetCompleted: false,
            customWorkoutTargetStepIndex: null,
            customWorkoutTargetStepLabel: "未启用自定义训练目标",
            customWorkoutTargetBlockType: null,
            customWorkoutTargetPowerWatts: null,
            customWorkoutTargetFtpPercent: null,
            customWorkoutTargetStartFtpPercent: null,
            customWorkoutTargetEndFtpPercent: null,
            customWorkoutTargetRemainingSeconds: null,
            customWorkoutTargetProgress: 0,
            pendingTrainerCommand: null,
            controlStatus: "坡度模拟待命：已基于当前路线实时梯度生成目标模拟坡度，开始骑行后按预先锁定模式下发 trainer 指令。"
        }
    };
}

function createInitialBleState() {
    const bluetoothSupported = Boolean(navigator.bluetooth);

    return {
        supported: bluetoothSupported,
        heartRate: {
            isConnecting: false,
            isConnected: false,
            statusLabel: bluetoothSupported ? "未连接" : "不支持",
            deviceName: bluetoothSupported ? "等待连接" : "当前浏览器不支持 Web Bluetooth",
            value: null,
            lastUpdated: null
        },
        powerMeter: {
            isConnecting: false,
            isConnected: false,
            statusLabel: bluetoothSupported ? "未连接" : "不支持",
            deviceName: bluetoothSupported ? "等待连接" : "当前浏览器不支持 Web Bluetooth",
            sourceType: "none",
            sourceLabel: bluetoothSupported ? "无可用功率源" : "不支持",
            externalConnected: false,
            externalConnecting: false,
            externalDeviceName: bluetoothSupported ? "等待连接" : "当前浏览器不支持 Web Bluetooth",
            power: null,
            cadence: null,
            averagePower: null,
            sampleCount: 0,
            powerTotal: 0,
            lastUpdated: null
        },
        trainer: {
            isConnecting: false,
            isConnected: false,
            controlActivating: false,
            controlReady: false,
            statusLabel: bluetoothSupported ? "未连接" : "不支持",
            deviceName: bluetoothSupported ? "等待连接" : "当前浏览器不支持 Web Bluetooth",
            lastUpdated: null
        },
        sampling: createInitialSensorSamplingState()
    };
}
