import { buildRoute, sanitizeSegments } from "../../domain/route/route-builder.js";
import { WORKOUT_MODES } from "../../domain/workout/workout-mode.js";
import { TRAINER_CONTROL_MODES } from "../../domain/workout/trainer-command.js";
import { clamp, normalizeText } from "../../shared/utils/common.js";

export const defaultRouteSegments = [
    { name: "热身缓坡", distanceKm: 2.5, gradePercent: 1.5 },
    { name: "主爬坡", distanceKm: 4.2, gradePercent: 4.8 },
    { name: "山顶起伏", distanceKm: 3.1, gradePercent: -1.2 },
    { name: "收尾平路", distanceKm: 2.8, gradePercent: 0.3 }
];

export const defaultSettings = {
    power: 220,
    mass: 78,
    ftp: 250,
    restingHr: 58,
    maxHr: 182,
    cda: 0.32,
    crr: 0.004,
    windSpeed: 0
};

export const defaultExportMetadata = {
    activityName: "Rider Tracker Virtual Ride",
    fitDescription: "Virtual ride generated by Rider Tracker.",
    repositoryUrl: "https://github.com/jsdylhw/rider-tracker",
    uploadEndpoint: ""
};

export function createInitialState(session) {
    const routeSegments = sanitizeSegments(defaultRouteSegments);
    const route = buildRoute(routeSegments);

    return {
        uiMode: "home",
        routeSegments,
        route,
        settings: { ...defaultSettings },
        workout: createInitialWorkoutState(),
        session,
        liveRide: createInitialLiveRideState(),
        ble: createInitialBleState(),
        exportMetadata: {
            ...defaultExportMetadata,
            ...(session?.exportMetadata ?? {})
        },
        hasPersistedSession: Boolean(session),
        pipConfig: {
            hr: true,
            power: true,
            time: true,
            np: true
        },
        statusText: "请先设置路线与模拟参数。"
    };
}

export function sanitizeSettings(settings) {
    return {
        power: clamp(settings.power, 80, 600, defaultSettings.power),
        mass: clamp(settings.mass, 40, 150, defaultSettings.mass),
        ftp: clamp(settings.ftp, 120, 450, defaultSettings.ftp),
        restingHr: clamp(settings.restingHr, 40, 100, defaultSettings.restingHr),
        maxHr: clamp(settings.maxHr, 120, 220, defaultSettings.maxHr),
        cda: clamp(settings.cda, 0.2, 0.8, defaultSettings.cda),
        crr: clamp(settings.crr, 0.001, 0.02, defaultSettings.crr),
        windSpeed: clamp(settings.windSpeed, -10, 10, defaultSettings.windSpeed)
    };
}

export function sanitizeExportMetadata(exportMetadata) {
    return {
        activityName: normalizeText(exportMetadata.activityName, defaultExportMetadata.activityName, 48),
        fitDescription: normalizeText(exportMetadata.fitDescription, defaultExportMetadata.fitDescription, 180),
        repositoryUrl: normalizeText(exportMetadata.repositoryUrl, defaultExportMetadata.repositoryUrl, 120),
        uploadEndpoint: normalizeText(exportMetadata.uploadEndpoint, defaultExportMetadata.uploadEndpoint, 300)
    };
}

function createInitialLiveRideState() {
    return {
        isActive: false,
        canStart: false,
        dashboardOpen: false,
        session: null,
        trainerControlMode: null,
        commandSequence: 0,
        startedAt: null,
        lastCompletedAt: null,
        statusMeta: "连接功率计后即可开始骑行。"
    };
}

function createInitialWorkoutState() {
    return {
        mode: WORKOUT_MODES.FREE_RIDE,
        gradeSimulation: {
            difficultyPercent: 75,
            lookaheadMeters: 120,
            maxUphillPercent: 10,
            maxDownhillPercent: -3,
            smoothingFactor: 0.35
        },
        runtime: {
            available: false,
            trainerControlMode: TRAINER_CONTROL_MODES.RESISTANCE,
            currentGradePercent: 0,
            lookaheadGradePercent: 0,
            targetTrainerGradePercent: 0,
            targetErgPowerWatts: null,
            targetResistanceLevel: 35,
            pendingTrainerCommand: null,
            controlStatus: "固定阻力待命：阻力等级 35%（开始骑行前已锁定控制模式）。"
        }
    };
}

function createInitialBleState() {
    const bluetoothSupported = Boolean(navigator.bluetooth);

    return {
        supported: bluetoothSupported,
        heartRate: {
            isConnecting: false,
            isConnected: false,
            statusLabel: bluetoothSupported ? "未连接" : "不支持",
            deviceName: bluetoothSupported ? "等待连接" : "当前浏览器不支持 Web Bluetooth",
            value: null,
            lastUpdated: null
        },
        powerMeter: {
            isConnecting: false,
            isConnected: false,
            statusLabel: bluetoothSupported ? "未连接" : "不支持",
            deviceName: bluetoothSupported ? "等待连接" : "当前浏览器不支持 Web Bluetooth",
            power: null,
            cadence: null,
            averagePower: null,
            sampleCount: 0,
            powerTotal: 0,
            lastUpdated: null
        }
    };
}
