export function createLiveView({ onCloseRideDashboard, onStartRide, onStopRide }) {
    const elements = {
        viewLive: document.getElementById("view-live"),
        liveCol1: document.getElementById("live-col-1"),
        connectHrBtn: document.getElementById("connectHrBtn"),
        connectPowerBtn: document.getElementById("connectPowerBtn"),
        connectTrainerBtn: document.getElementById("connectTrainerBtn"),
        workoutModeForm: document.getElementById("workoutModeForm"),
        workoutModeSelect: document.getElementById("workoutModeSelect"),
        workoutModeRadios: [...document.querySelectorAll('input[name="workoutMode"]')],
        gradeDifficultyInput: document.getElementById("gradeDifficultyInput"),
        gradeLookaheadInput: document.getElementById("gradeLookaheadInput"),
        maxUphillInput: document.getElementById("maxUphillInput"),
        maxDownhillInput: document.getElementById("maxDownhillInput"),
        gradeSmoothingInput: document.getElementById("gradeSmoothingInput"),
        ergTargetPowerInput: document.getElementById("ergTargetPowerInput"),
        ergConfirmationRequiredInput: document.getElementById("ergConfirmationRequiredInput"),
        resistanceLevelInput: document.getElementById("resistanceLevelInput"),
        workoutModeLabel: document.getElementById("workoutModeLabel"),
        trainerTargetLabel: document.getElementById("trainerTargetLabel"),
        targetTrainerGradeValue: document.getElementById("targetTrainerGradeValue"),
        workoutControlStatus: document.getElementById("workoutControlStatus"),
        customWorkoutTargetEnabled: document.getElementById("customWorkoutTargetEnabled"),
        customWorkoutTargetPanel: document.getElementById("customWorkoutTargetPanel"),
        customWorkoutTargetEditor: document.getElementById("customWorkoutTargetEditor"),
        addCustomWorkoutTargetStepBtn: document.getElementById("addCustomWorkoutTargetStepBtn"),
        customWorkoutTargetTableBody: document.getElementById("customWorkoutTargetTableBody"),
        customWorkoutTargetStatus: document.getElementById("customWorkoutTargetStatus"),
        openRideDashboardBtn: document.getElementById("openRideDashboardBtn"),
        hrDeviceStatus: document.getElementById("hrDeviceStatus"),
        hrDeviceName: document.getElementById("hrDeviceName"),
        powerDeviceStatus: document.getElementById("powerDeviceStatus"),
        powerDeviceName: document.getElementById("powerDeviceName"),
        trainerDeviceStatus: document.getElementById("trainerDeviceStatus"),
        trainerDeviceName: document.getElementById("trainerDeviceName"),
        rideStatusLabel: document.getElementById("rideStatusLabel"),
        rideStatusMeta: document.getElementById("rideStatusMeta"),
        rideSegmentLabel: document.getElementById("rideSegmentLabel"),
        rideSegmentMeta: document.getElementById("rideSegmentMeta"),
        liveHeartRateDisplay: document.getElementById("liveHeartRateDisplay"),
        livePowerDisplay: document.getElementById("livePowerDisplay"),
        liveCadenceDisplay: document.getElementById("liveCadenceDisplay"),
        liveAvgPowerDisplay: document.getElementById("liveAvgPowerDisplay"),
        liveSpeedDisplay: document.getElementById("liveSpeedDisplay"),
        liveDistanceDisplay: document.getElementById("liveDistanceDisplay"),
        rideDashboard: document.getElementById("rideDashboard"),
        rideDashboardTitle: document.getElementById("rideDashboardTitle"),
        rideDashboardSubtitle: document.getElementById("rideDashboardSubtitle"),
        rideProgressHeadline: document.getElementById("rideProgressHeadline"),
        rideProgressBar: document.getElementById("rideProgressBar"),
        rideProgressDistance: document.getElementById("rideProgressDistance"),
        rideProgressSegment: document.getElementById("rideProgressSegment"),
        rideDashboardMap: document.getElementById("rideDashboardMap"),
        dashboardAvgHr: document.getElementById("dashboardAvgHr"),
        dashboardAvgPower: document.getElementById("dashboardAvgPower"),
        dashboardMaxPower: document.getElementById("dashboardMaxPower"),
        dashboardTss: document.getElementById("dashboardTss"),
        dashboardCurrentSpeed: document.getElementById("dashboardCurrentSpeed"),
        dashboardCurrentGrade: document.getElementById("dashboardCurrentGrade"),
        startRideDashboardBtn: document.getElementById("startRideDashboardBtn"),
        closeRideDashboardBtn: document.getElementById("closeRideDashboardBtn"),
        immersiveBackBtn: document.getElementById("immersiveBackBtn"),
        stopRideDashboardBtn: document.getElementById("stopRideDashboardBtn"),
        dashboardMetricsGrid: document.getElementById("dashboardMetricsGrid"),
        immersiveMetricsGrid: document.getElementById("immersiveMetricsGrid"),
        customizeMetricsBtn: document.getElementById("customizeMetricsBtn"),
        metricsCustomizer: document.getElementById("metricsCustomizer"),
        metricAddSelect: document.getElementById("metricAddSelect"),
        addMetricBtn: document.getElementById("addMetricBtn"),
        selectedMetricsList: document.getElementById("selectedMetricsList"),
        liveElevationCard: document.getElementById("liveElevationCard"),
        rideDashboardElevationChart: document.getElementById("rideDashboardElevationChart"),
        trainerPushGradeValue: document.getElementById("trainerPushGradeValue"),
        trainerPushGradeMeta: document.getElementById("trainerPushGradeMeta"),
        deviceControlsPanel: document.getElementById("deviceControlsPanel"),
        loadStreetViewBtn: document.getElementById("loadStreetViewBtn"),
        streetViewApiKey: document.getElementById("streetViewApiKey"),
        immersiveStreetViewBtn: document.getElementById("immersiveStreetViewBtn"),
        streetViewContainer: document.getElementById("streetViewContainer"),
        svPano1: document.getElementById("svPano1"),
        svPano2: document.getElementById("svPano2"),
        trajectoryCard: document.getElementById("trajectoryCard"),
        streetViewTrajectorySvg: document.getElementById("streetViewTrajectorySvg"),
        workoutTargetHudCard: document.getElementById("workoutTargetHudCard"),
        workoutTargetHudGrid: document.getElementById("workoutTargetHudGrid"),
        workoutTargetChart: document.getElementById("workoutTargetChart"),
        liveWorkoutTargetCard: document.getElementById("liveWorkoutTargetCard")
    };

    bind(elements.closeRideDashboardBtn, "click", onCloseRideDashboard);
    bind(elements.startRideDashboardBtn, "click", onStartRide);
    bind(elements.stopRideDashboardBtn, "click", onStopRide);

    return { elements };
}

function bind(el, event, handler) {
    if (el) el.addEventListener(event, handler);
}
