import { createPipController } from "../../pip.js";
import { createHeartRateMonitor } from "../adapters/bluetooth/heart-rate-monitor.js";
import { createPowerMeter } from "../adapters/bluetooth/power-meter.js";
import { createStore } from "./store/app-store.js";
import { exportSessionAsFit } from "../adapters/export/fit-exporter.js";
import { saveLastSession, loadLastSession } from "../adapters/storage/session-storage.js";
import { parseGpx } from "../domain/course/gpx-parser.js";
import { buildRoute, sanitizeSegments } from "../domain/course/route-builder.js";
import { advanceLiveRideSession, createLiveRideSession } from "../domain/session/live-ride-session.js";
import { simulateRide } from "../domain/session/simulator.js";
import { downloadBinary, downloadJson, formatDuration, formatNumber } from "../shared/format.js";
import { createMainView } from "../ui/renderers/main-view.js";

const defaultRouteSegments = [
    { name: "热身缓坡", distanceKm: 2.5, gradePercent: 1.5 },
    { name: "主爬坡", distanceKm: 4.2, gradePercent: 4.8 },
    { name: "山顶起伏", distanceKm: 3.1, gradePercent: -1.2 },
    { name: "收尾平路", distanceKm: 2.8, gradePercent: 0.3 }
];

const defaultSettings = {
    power: 220,
    mass: 78,
    ftp: 250,
    restingHr: 58,
    maxHr: 182,
    cda: 0.32,
    crr: 0.004,
    windSpeed: 0
};

const defaultExportMetadata = {
    activityName: "Rider Tracker Virtual Ride",
    fitDescription: "Virtual ride generated by Rider Tracker.",
    repositoryUrl: "https://github.com/jsdylhw/rider-tracker"
};

const persistedSession = loadLastSession();

const store = createStore(createInitialState(persistedSession));

const heartRateMonitor = createHeartRateMonitor({
    onData: handleHeartRateData,
    onStatus: handleHeartRateStatus
});

const powerMeter = createPowerMeter({
    onData: handlePowerMeterData,
    onStatus: handlePowerMeterStatus
});

let liveRideTimerId = null;

const pipController = createPipController({
    button: document.getElementById("pipBtn"),
    template: document.getElementById("pip-template"),
    getData: () => buildPipData(store.getState())
});

createMainView({
    store,
    pipController,
    onSetUiMode: handleSetUiMode,
    onAddSegment: handleAddSegment,
    onResetRoute: handleResetRoute,
    onToggleHeartRate: handleToggleHeartRate,
    onTogglePowerMeter: handleTogglePowerMeter,
    onOpenRideDashboard: handleOpenRideDashboard,
    onCloseRideDashboard: handleCloseRideDashboard,
    onStartRide: handleStartRide,
    onStopRide: handleStopRide,
    onRunSimulation: handleRunSimulation,
    onDownloadSession: handleDownloadSession,
    onDownloadFit: handleDownloadFit,
    onImportGpx: handleImportGpx,
    onUpdateRouteSegment: handleUpdateRouteSegment,
    onRemoveRouteSegment: handleRemoveRouteSegment,
    onUpdateSettings: handleUpdateSettings,
    onUpdateExportMetadata: handleUpdateExportMetadata,
    onUpdatePipConfig: handleUpdatePipConfig
});

store.setState((state) => ({
    ...state,
    statusText: persistedSession
        ? `已恢复最近一次模拟：${formatDuration(persistedSession.summary.elapsedSeconds)} / ${formatNumber(persistedSession.summary.distanceKm, 2)} km`
        : state.statusText
}));

fetch("user-profile.json")
    .then((response) => {
        if (!response.ok) {
            throw new Error("Local profile not found");
        }
        return response.json();
    })
    .then((profile) => {
        store.setState((state) => ({
            ...state,
            settings: sanitizeSettings({
                ...state.settings,
                ...profile
            }),
            statusText: "已加载本地用户配置 user-profile.json"
        }));
    })
    .catch((error) => {
        console.info("未能加载本地 user-profile.json，使用默认设置。", error);
    });

function handleSetUiMode(mode) {
    store.setState((state) => ({
        ...state,
        uiMode: mode
    }));
}

function handleAddSegment() {
    store.setState((state) => {
        const routeSegments = sanitizeSegments([
            ...state.routeSegments,
            { name: `路段 ${state.routeSegments.length + 1}`, distanceKm: 1.5, gradePercent: 0 }
        ]);

        return buildStateWithRoute(state, routeSegments, "已新增一段路线。");
    });
}

function handleResetRoute() {
    store.setState((state) => buildStateWithRoute(state, sanitizeSegments(defaultRouteSegments), "已恢复默认手工路线。"));
}

function handleUpdateRouteSegment(segmentId, field, value) {
    store.setState((state) => {
        const routeSegments = sanitizeSegments(
            state.routeSegments.map((segment) => (
                segment.id === segmentId ? { ...segment, [field]: value } : segment
            ))
        );

        return buildStateWithRoute(state, routeSegments, "路线已更新。");
    });
}

function handleRemoveRouteSegment(segmentId) {
    store.setState((state) => {
        const nextSegments = state.routeSegments.filter((segment) => segment.id !== segmentId);
        const routeSegments = sanitizeSegments(nextSegments.length > 0 ? nextSegments : defaultRouteSegments.slice(0, 1));
        return buildStateWithRoute(state, routeSegments, "已移除选中路段。");
    });
}

function handleUpdateSettings(partialSettings) {
    store.setState((state) => {
        const mergedSettings = { ...state.settings, ...partialSettings };
        return {
            ...state,
            settings: sanitizeSettings(mergedSettings),
            statusText: "设置已更新。"
        };
    });
}

function handleUpdatePipConfig(key, checked) {
    store.setState((state) => ({
        ...state,
        pipConfig: {
            ...state.pipConfig,
            [key]: checked
        }
    }));
}

function handleStartRide() {
    const state = store.getState();

    if (!state.liveRide.canStart || state.liveRide.isActive) {
        return;
    }

    const startedAt = new Date().toISOString();
    const session = createLiveRideSession({
        route: state.route,
        settings: state.settings,
        startedAt,
        initialHeartRate: state.ble.heartRate.value
    });
    session.exportMetadata = state.exportMetadata;

    clearInterval(liveRideTimerId);
    liveRideTimerId = window.setInterval(tickLiveRide, 1000);

    store.setState((currentState) => ({
        ...currentState,
        liveRide: {
            ...currentState.liveRide,
            isActive: true,
            dashboardOpen: true,
            session,
            startedAt,
            statusMeta: "正在根据实时功率和路线坡度更新速度。"
        },
        statusText: "已开始骑行，速度将根据实时功率和当前路线坡度计算。"
    }));
}

function handleStopRide() {
    const state = store.getState();

    if (!state.liveRide.isActive) {
        return;
    }

    clearInterval(liveRideTimerId);
    liveRideTimerId = null;

    const completedSession = state.liveRide.session;

    if (completedSession) {
        saveLastSession(completedSession);
    }

    store.setState((currentState) => ({
        ...currentState,
        session: completedSession ?? currentState.session,
        hasPersistedSession: Boolean(completedSession) || currentState.hasPersistedSession,
        liveRide: {
            ...currentState.liveRide,
            isActive: false,
            dashboardOpen: false,
            lastCompletedAt: new Date().toISOString(),
            statusMeta: completedSession
                ? `骑行结束：${formatNumber(completedSession.summary.distanceKm, 2)} km / 平均速度 ${formatNumber(completedSession.summary.averageSpeedKph, 1)} km/h`
                : "骑行已停止。"
        },
        statusText: completedSession
            ? `骑行结束：${formatNumber(completedSession.summary.distanceKm, 2)} km / 平均速度 ${formatNumber(completedSession.summary.averageSpeedKph, 1)} km/h`
            : "骑行已停止。"
    }));
}

function handleOpenRideDashboard() {
    store.setState((state) => ({
        ...state,
        liveRide: {
            ...state.liveRide,
            dashboardOpen: true
        }
    }));
}

function handleCloseRideDashboard() {
    store.setState((state) => ({
        ...state,
        liveRide: {
            ...state.liveRide,
            dashboardOpen: false
        }
    }));
}

function tickLiveRide() {
    const state = store.getState();

    if (!state.liveRide.isActive || !state.liveRide.session) {
        clearInterval(liveRideTimerId);
        liveRideTimerId = null;
        return;
    }

    const currentPower = state.ble.powerMeter.power ?? 0;
    const currentHeartRate = state.ble.heartRate.value;
    const currentCadence = state.ble.powerMeter.cadence;

    const nextSession = advanceLiveRideSession({
        session: state.liveRide.session,
        power: currentPower,
        heartRate: currentHeartRate,
        cadence: currentCadence,
        dt: 1
    });

    store.setState((currentState) => ({
        ...currentState,
        liveRide: {
            ...currentState.liveRide,
            session: nextSession,
            statusMeta: `已骑行 ${formatDuration(nextSession.summary.elapsedSeconds)}，当前速度 ${formatNumber(nextSession.summary.currentSpeedKph, 1)} km/h`
        }
    }));
}

async function handleToggleHeartRate() {
    try {
        await heartRateMonitor.toggle();
    } catch (error) {
        console.error("心率带连接失败", error);
        store.setState((state) => ({
            ...state,
            ble: {
                ...state.ble,
                heartRate: {
                    ...state.ble.heartRate,
                    isConnecting: false,
                    statusLabel: "连接失败",
                    deviceName: error.message
                }
            },
            statusText: `心率带连接失败：${error.message}`
        }));
    }
}

async function handleTogglePowerMeter() {
    try {
        await powerMeter.toggle();
    } catch (error) {
        console.error("功率计连接失败", error);
        store.setState((state) => ({
            ...state,
            ble: {
                ...state.ble,
                powerMeter: {
                    ...state.ble.powerMeter,
                    isConnecting: false,
                    statusLabel: "连接失败",
                    deviceName: error.message
                }
            },
            statusText: `功率计连接失败：${error.message}`
        }));
    }
}

function handleHeartRateStatus(status) {
    store.setState((state) => ({
        ...state,
        ble: {
            ...state.ble,
            heartRate: {
                ...state.ble.heartRate,
                isConnecting: status.type === "connecting",
                isConnected: status.type === "connected",
                statusLabel: mapStatusLabel(status.type),
                deviceName: status.deviceName ?? (status.type === "disconnected" ? "等待连接" : status.message),
                value: status.type === "disconnected" ? null : state.ble.heartRate.value
            }
        },
        statusText: status.message
    }));
}

function handleHeartRateData(data) {
    store.setState((state) => ({
        ...state,
        ble: {
            ...state.ble,
            heartRate: {
                ...state.ble.heartRate,
                value: data.heartRate,
                lastUpdated: data.timestamp
            }
        }
    }));
}

function handlePowerMeterStatus(status) {
    const wasActive = store.getState().liveRide.isActive;

    store.setState((state) => ({
        ...state,
        ble: {
            ...state.ble,
            powerMeter: {
                ...state.ble.powerMeter,
                isConnecting: status.type === "connecting",
                isConnected: status.type === "connected",
                statusLabel: mapStatusLabel(status.type),
                deviceName: status.deviceName ?? (status.type === "disconnected" ? "等待连接" : status.message),
                power: status.type === "disconnected" ? null : state.ble.powerMeter.power,
                cadence: status.type === "disconnected" ? null : state.ble.powerMeter.cadence,
                averagePower: status.type === "disconnected" ? null : state.ble.powerMeter.averagePower,
                sampleCount: status.type === "disconnected" ? 0 : state.ble.powerMeter.sampleCount,
                powerTotal: status.type === "disconnected" ? 0 : state.ble.powerMeter.powerTotal
            }
        },
        liveRide: {
            ...state.liveRide,
            canStart: status.type === "connected" || state.liveRide.isActive // 如果已经在骑行中，允许断开后保持状态
        },
        statusText: status.message
    }));
}

function handlePowerMeterData(data) {
    store.setState((state) => {
        const sampleCount = state.ble.powerMeter.sampleCount + 1;
        const powerTotal = state.ble.powerMeter.powerTotal + data.power;

        return {
            ...state,
            ble: {
                ...state.ble,
                powerMeter: {
                    ...state.ble.powerMeter,
                    power: data.power,
                    cadence: data.cadence ?? state.ble.powerMeter.cadence,
                    averagePower: Math.round(powerTotal / sampleCount),
                    sampleCount,
                    powerTotal,
                    lastUpdated: data.timestamp
                }
            }
        };
    });
}

function handleUpdateExportMetadata(exportMetadata) {
    store.setState((state) => ({
        ...state,
        exportMetadata: {
            ...state.exportMetadata,
            ...sanitizeExportMetadata(exportMetadata)
        },
        statusText: "FIT 导出信息已更新。"
    }));
}

async function handleImportGpx(file) {
    try {
        const xmlText = await file.text();
        const route = parseGpx(xmlText);

        store.setState((state) => ({
            ...state,
            route,
            routeSegments: route.segments,
            statusText: `已导入 GPX：${route.name}，距离 ${formatNumber(route.totalDistanceMeters / 1000, 2)} km`
        }));
    } catch (error) {
        console.error("GPX 导入失败", error);
        store.setState((state) => ({
            ...state,
            statusText: `GPX 导入失败：${extractErrorMessage(error)}`
        }));
    }
}

function handleRunSimulation() {
    const state = store.getState();
    const session = {
        ...simulateRide({
            route: state.route,
            settings: state.settings
        }),
        exportMetadata: state.exportMetadata
    };

    saveLastSession(session);

    store.setState((currentState) => ({
        ...currentState,
        session,
        hasPersistedSession: true,
        statusText: `模拟完成：${formatNumber(session.summary.distanceKm, 2)} km / 平均速度 ${formatNumber(session.summary.averageSpeedKph, 1)} km/h`
    }));
}

function handleDownloadSession() {
    const { session } = store.getState();

    if (!session) {
        return;
    }

    const timestamp = session.createdAt.replaceAll(":", "-").split(".")[0];
    downloadJson(`ride-simulation-${timestamp}.json`, session);

    store.setState((state) => ({
        ...state,
        statusText: "已导出当前模拟数据 JSON。"
    }));
}

async function handleDownloadFit() {
    const { session, exportMetadata } = store.getState();

    if (!session) {
        return;
    }

    store.setState((state) => ({
        ...state,
        statusText: "正在生成 FIT 文件..."
    }));

    try {
        const fitBytes = await exportSessionAsFit(session, exportMetadata);
        const timestamp = session.createdAt.replaceAll(":", "-").split(".")[0];
        downloadBinary(`virtual-ride-${timestamp}.fit`, fitBytes, "application/vnd.ant.fit");

        store.setState((state) => ({
            ...state,
            statusText: "已导出 FIT 文件，包含虚拟骑行说明和仓库地址。"
        }));
    } catch (error) {
        console.error("FIT 导出失败", error);
        const errorMessage = extractErrorMessage(error);
        store.setState((state) => ({
            ...state,
            statusText: `FIT 导出失败：${errorMessage}`
        }));
    }
}

function createInitialState(session) {
    const routeSegments = sanitizeSegments(defaultRouteSegments);
    const route = buildRoute(routeSegments);

    let initialMode = 'home';
    const path = window.location.pathname;
    if (path.includes('simulation.html')) {
        initialMode = 'simulation';
    } else if (path.includes('live.html')) {
        initialMode = 'live';
    }

    return {
        uiMode: initialMode,
        routeSegments,
        route,
        settings: { ...defaultSettings },
        session,
        liveRide: createInitialLiveRideState(),
        ble: createInitialBleState(),
        exportMetadata: {
            ...defaultExportMetadata,
            ...(session?.exportMetadata ?? {})
        },
        hasPersistedSession: Boolean(session),
        pipConfig: {
            hr: true,
            power: true,
            time: true,
            np: true
        },
        statusText: "请先设置路线与模拟参数。"
    };
}

function buildStateWithRoute(state, routeSegments, statusText) {
    return {
        ...state,
        routeSegments,
        route: buildRoute(routeSegments),
        statusText
    };
}

function sanitizeSettings(settings) {
    return {
        power: clamp(settings.power, 80, 600, defaultSettings.power),
        mass: clamp(settings.mass, 40, 150, defaultSettings.mass),
        ftp: clamp(settings.ftp, 120, 450, defaultSettings.ftp),
        restingHr: clamp(settings.restingHr, 40, 100, defaultSettings.restingHr),
        maxHr: clamp(settings.maxHr, 120, 220, defaultSettings.maxHr),
        cda: clamp(settings.cda, 0.2, 0.8, defaultSettings.cda),
        crr: clamp(settings.crr, 0.001, 0.02, defaultSettings.crr),
        windSpeed: clamp(settings.windSpeed, -10, 10, defaultSettings.windSpeed)
    };
}

function sanitizeExportMetadata(exportMetadata) {
    return {
        activityName: normalizeText(exportMetadata.activityName, defaultExportMetadata.activityName, 48),
        fitDescription: normalizeText(exportMetadata.fitDescription, defaultExportMetadata.fitDescription, 180),
        repositoryUrl: normalizeText(exportMetadata.repositoryUrl, defaultExportMetadata.repositoryUrl, 120)
    };
}

function clamp(value, min, max, fallback) {
    const parsed = Number(value);

    if (Number.isNaN(parsed)) {
        return fallback;
    }

    return Math.min(max, Math.max(min, parsed));
}

function normalizeText(value, fallback, maxLength) {
    const text = String(value ?? "").trim();
    return (text || fallback).slice(0, maxLength);
}

function extractErrorMessage(error) {
    if (error?.cause?.cause?.message) {
        return error.cause.cause.message;
    }

    if (error?.cause?.message) {
        return error.cause.message;
    }

    if (error?.message) {
        return error.message;
    }

    return "未知错误";
}

function buildPipData(state) {
    const liveRecord = state.liveRide.session?.records.at(-1);
    const liveSummary = state.liveRide.session?.summary;
    const route = state.liveRide.session?.route ?? state.route;
    
    const liveHeartRate = state.ble.heartRate.value;
    const livePower = state.ble.powerMeter.power;
    const liveCadence = state.ble.powerMeter.cadence;

    const totalDistanceKm = route ? route.totalDistanceMeters / 1000 : 0;
    const distanceKm = liveSummary?.distanceKm ?? 0;
    const remainingKm = Math.max(0, totalDistanceKm - distanceKm);

    return {
        distance: formatNumber(distanceKm, 2),
        remaining: formatNumber(remainingKm, 2),
        speed: liveSummary ? formatNumber(liveSummary.currentSpeedKph, 1) : "--",
        power: livePower !== null ? String(livePower) : "--",
        hr: liveHeartRate !== null ? String(liveHeartRate) : "--",
        cadence: liveCadence !== null ? String(liveCadence) : "--",
        route: route,
        currentRecord: liveRecord ?? null
    };
}

function createInitialLiveRideState() {
    return {
        isActive: false,
        canStart: false,
        dashboardOpen: false,
        session: null,
        startedAt: null,
        lastCompletedAt: null,
        statusMeta: "连接功率计后即可开始骑行。"
    };
}

function createInitialBleState() {
    const bluetoothSupported = Boolean(navigator.bluetooth);

    return {
        supported: bluetoothSupported,
        heartRate: {
            isConnecting: false,
            isConnected: false,
            statusLabel: bluetoothSupported ? "未连接" : "不支持",
            deviceName: bluetoothSupported ? "等待连接" : "当前浏览器不支持 Web Bluetooth",
            value: null,
            lastUpdated: null
        },
        powerMeter: {
            isConnecting: false,
            isConnected: false,
            statusLabel: bluetoothSupported ? "未连接" : "不支持",
            deviceName: bluetoothSupported ? "等待连接" : "当前浏览器不支持 Web Bluetooth",
            power: null,
            cadence: null,
            averagePower: null,
            sampleCount: 0,
            powerTotal: 0,
            lastUpdated: null
        }
    };
}

function mapStatusLabel(type) {
    if (type === "connected") {
        return "已连接";
    }

    if (type === "connecting") {
        return "连接中";
    }

    return "未连接";
}
