import { createPipController } from "../../pip.js";
import { createHeartRateMonitor } from "../adapters/bluetooth/heart-rate-monitor.js";
import { createPowerMeter } from "../adapters/bluetooth/power-meter.js";
import { createStore } from "./store/app-store.js";
import { exportSessionAsFit } from "../adapters/export/fit-exporter.js";
import { saveLastSession, loadLastSession } from "../adapters/storage/session-storage.js";
import { buildRoute, sanitizeSegments } from "../domain/course/route-builder.js";
import { simulateRide } from "../domain/session/simulator.js";
import { downloadBinary, downloadJson, formatDuration, formatNumber } from "../shared/format.js";
import { createMainView } from "../ui/renderers/main-view.js";

const defaultRouteSegments = [
    { name: "热身缓坡", distanceKm: 2.5, gradePercent: 1.5 },
    { name: "主爬坡", distanceKm: 4.2, gradePercent: 4.8 },
    { name: "山顶起伏", distanceKm: 3.1, gradePercent: -1.2 },
    { name: "收尾平路", distanceKm: 2.8, gradePercent: 0.3 }
];

const defaultSettings = {
    power: 220,
    durationMinutes: 45,
    mass: 78,
    restingHr: 58,
    maxHr: 182,
    cda: 0.32,
    crr: 0.004,
    windSpeed: 0
};

const defaultExportMetadata = {
    activityName: "Rider Tracker Virtual Ride",
    fitDescription: "Virtual ride generated by Rider Tracker.",
    repositoryUrl: "https://github.com/jsdylhw/rider-tracker"
};

const persistedSession = loadLastSession();

const store = createStore(createInitialState(persistedSession));

const heartRateMonitor = createHeartRateMonitor({
    onData: handleHeartRateData,
    onStatus: handleHeartRateStatus
});

const powerMeter = createPowerMeter({
    onData: handlePowerMeterData,
    onStatus: handlePowerMeterStatus
});

const pipController = createPipController({
    button: document.getElementById("pipBtn"),
    template: document.getElementById("pip-template"),
    getData: () => buildPipData(store.getState()),
    getConfig: () => store.getState().pipConfig
});

createMainView({
    store,
    pipController,
    onAddSegment: handleAddSegment,
    onResetRoute: handleResetRoute,
    onToggleHeartRate: handleToggleHeartRate,
    onTogglePowerMeter: handleTogglePowerMeter,
    onRunSimulation: handleRunSimulation,
    onDownloadSession: handleDownloadSession,
    onDownloadFit: handleDownloadFit,
    onUpdateRouteSegment: handleUpdateRouteSegment,
    onRemoveRouteSegment: handleRemoveRouteSegment,
    onUpdateSettings: handleUpdateSettings,
    onUpdateExportMetadata: handleUpdateExportMetadata,
    onUpdatePipConfig: handleUpdatePipConfig
});

store.setState((state) => ({
    ...state,
    statusText: persistedSession
        ? `已恢复最近一次模拟：${formatDuration(persistedSession.summary.elapsedSeconds)} / ${formatNumber(persistedSession.summary.distanceKm, 2)} km`
        : state.statusText
}));

function handleAddSegment() {
    store.setState((state) => {
        const routeSegments = sanitizeSegments([
            ...state.routeSegments,
            { name: `路段 ${state.routeSegments.length + 1}`, distanceKm: 1.5, gradePercent: 0 }
        ]);

        return buildStateWithRoute(state, routeSegments, "已新增一段路线。");
    });
}

function handleResetRoute() {
    store.setState((state) => buildStateWithRoute(state, sanitizeSegments(defaultRouteSegments), "已恢复默认路线。"));
}

function handleUpdateRouteSegment(segmentId, field, value) {
    store.setState((state) => {
        const routeSegments = sanitizeSegments(
            state.routeSegments.map((segment) => (
                segment.id === segmentId ? { ...segment, [field]: value } : segment
            ))
        );

        return buildStateWithRoute(state, routeSegments, "路线已更新。");
    });
}

function handleRemoveRouteSegment(segmentId) {
    store.setState((state) => {
        const nextSegments = state.routeSegments.filter((segment) => segment.id !== segmentId);
        const routeSegments = sanitizeSegments(nextSegments.length > 0 ? nextSegments : defaultRouteSegments.slice(0, 1));
        return buildStateWithRoute(state, routeSegments, "已移除选中路段。");
    });
}

function handleUpdateSettings(settings) {
    store.setState((state) => ({
        ...state,
        settings: {
            ...state.settings,
            ...sanitizeSettings(settings)
        },
        statusText: "模拟参数已更新，可直接运行模拟。"
    }));
}

function handleUpdatePipConfig(key, checked) {
    store.setState((state) => ({
        ...state,
        pipConfig: {
            ...state.pipConfig,
            [key]: checked
        }
    }));
}

async function handleToggleHeartRate() {
    try {
        await heartRateMonitor.toggle();
    } catch (error) {
        console.error("心率带连接失败", error);
        store.setState((state) => ({
            ...state,
            ble: {
                ...state.ble,
                heartRate: {
                    ...state.ble.heartRate,
                    isConnecting: false,
                    statusLabel: "连接失败",
                    deviceName: error.message
                }
            },
            statusText: `心率带连接失败：${error.message}`
        }));
    }
}

async function handleTogglePowerMeter() {
    try {
        await powerMeter.toggle();
    } catch (error) {
        console.error("功率计连接失败", error);
        store.setState((state) => ({
            ...state,
            ble: {
                ...state.ble,
                powerMeter: {
                    ...state.ble.powerMeter,
                    isConnecting: false,
                    statusLabel: "连接失败",
                    deviceName: error.message
                }
            },
            statusText: `功率计连接失败：${error.message}`
        }));
    }
}

function handleHeartRateStatus(status) {
    store.setState((state) => ({
        ...state,
        ble: {
            ...state.ble,
            heartRate: {
                ...state.ble.heartRate,
                isConnecting: status.type === "connecting",
                isConnected: status.type === "connected",
                statusLabel: mapStatusLabel(status.type),
                deviceName: status.deviceName ?? (status.type === "disconnected" ? "等待连接" : status.message),
                value: status.type === "disconnected" ? null : state.ble.heartRate.value
            }
        },
        statusText: status.message
    }));
}

function handleHeartRateData(data) {
    store.setState((state) => ({
        ...state,
        ble: {
            ...state.ble,
            heartRate: {
                ...state.ble.heartRate,
                value: data.heartRate,
                lastUpdated: data.timestamp
            }
        }
    }));
}

function handlePowerMeterStatus(status) {
    store.setState((state) => ({
        ...state,
        ble: {
            ...state.ble,
            powerMeter: {
                ...state.ble.powerMeter,
                isConnecting: status.type === "connecting",
                isConnected: status.type === "connected",
                statusLabel: mapStatusLabel(status.type),
                deviceName: status.deviceName ?? (status.type === "disconnected" ? "等待连接" : status.message),
                power: status.type === "disconnected" ? null : state.ble.powerMeter.power,
                cadence: status.type === "disconnected" ? null : state.ble.powerMeter.cadence,
                averagePower: status.type === "disconnected" ? null : state.ble.powerMeter.averagePower,
                sampleCount: status.type === "disconnected" ? 0 : state.ble.powerMeter.sampleCount,
                powerTotal: status.type === "disconnected" ? 0 : state.ble.powerMeter.powerTotal
            }
        },
        statusText: status.message
    }));
}

function handlePowerMeterData(data) {
    store.setState((state) => {
        const sampleCount = state.ble.powerMeter.sampleCount + 1;
        const powerTotal = state.ble.powerMeter.powerTotal + data.power;

        return {
            ...state,
            ble: {
                ...state.ble,
                powerMeter: {
                    ...state.ble.powerMeter,
                    power: data.power,
                    cadence: data.cadence ?? state.ble.powerMeter.cadence,
                    averagePower: Math.round(powerTotal / sampleCount),
                    sampleCount,
                    powerTotal,
                    lastUpdated: data.timestamp
                }
            }
        };
    });
}

function handleUpdateExportMetadata(exportMetadata) {
    store.setState((state) => ({
        ...state,
        exportMetadata: {
            ...state.exportMetadata,
            ...sanitizeExportMetadata(exportMetadata)
        },
        statusText: "FIT 导出信息已更新。"
    }));
}

function handleRunSimulation() {
    const state = store.getState();
    const session = {
        ...simulateRide({
            route: state.route,
            settings: state.settings
        }),
        exportMetadata: state.exportMetadata
    };

    saveLastSession(session);

    store.setState((currentState) => ({
        ...currentState,
        session,
        hasPersistedSession: true,
        statusText: `模拟完成：${formatNumber(session.summary.distanceKm, 2)} km / 平均速度 ${formatNumber(session.summary.averageSpeedKph, 1)} km/h`
    }));
}

function handleDownloadSession() {
    const { session } = store.getState();

    if (!session) {
        return;
    }

    const timestamp = session.createdAt.replaceAll(":", "-").split(".")[0];
    downloadJson(`ride-simulation-${timestamp}.json`, session);

    store.setState((state) => ({
        ...state,
        statusText: "已导出当前模拟数据 JSON。"
    }));
}

async function handleDownloadFit() {
    const { session, exportMetadata } = store.getState();

    if (!session) {
        return;
    }

    store.setState((state) => ({
        ...state,
        statusText: "正在生成 FIT 文件..."
    }));

    try {
        const fitBytes = await exportSessionAsFit(session, exportMetadata);
        const timestamp = session.createdAt.replaceAll(":", "-").split(".")[0];
        downloadBinary(`virtual-ride-${timestamp}.fit`, fitBytes, "application/vnd.ant.fit");

        store.setState((state) => ({
            ...state,
            statusText: "已导出 FIT 文件，包含虚拟骑行说明和仓库地址。"
        }));
    } catch (error) {
        console.error("FIT 导出失败", error);
        const errorMessage = extractErrorMessage(error);
        store.setState((state) => ({
            ...state,
            statusText: `FIT 导出失败：${errorMessage}`
        }));
    }
}

function createInitialState(session) {
    const routeSegments = sanitizeSegments(defaultRouteSegments);
    const route = buildRoute(routeSegments);

    return {
        routeSegments,
        route,
        settings: { ...defaultSettings },
        session,
        ble: createInitialBleState(),
        exportMetadata: {
            ...defaultExportMetadata,
            ...(session?.exportMetadata ?? {})
        },
        hasPersistedSession: Boolean(session),
        pipConfig: {
            hr: true,
            power: true,
            time: true,
            np: true
        },
        statusText: "请先设置路线与模拟参数。"
    };
}

function buildStateWithRoute(state, routeSegments, statusText) {
    return {
        ...state,
        routeSegments,
        route: buildRoute(routeSegments),
        statusText
    };
}

function sanitizeSettings(settings) {
    return {
        power: clamp(settings.power, 80, 600, defaultSettings.power),
        durationMinutes: clamp(settings.durationMinutes, 5, 360, defaultSettings.durationMinutes),
        mass: clamp(settings.mass, 40, 150, defaultSettings.mass),
        restingHr: clamp(settings.restingHr, 40, 100, defaultSettings.restingHr),
        maxHr: clamp(settings.maxHr, 120, 220, defaultSettings.maxHr),
        cda: clamp(settings.cda, 0.2, 0.8, defaultSettings.cda),
        crr: clamp(settings.crr, 0.001, 0.02, defaultSettings.crr),
        windSpeed: clamp(settings.windSpeed, -10, 10, defaultSettings.windSpeed)
    };
}

function sanitizeExportMetadata(exportMetadata) {
    return {
        activityName: normalizeText(exportMetadata.activityName, defaultExportMetadata.activityName, 48),
        fitDescription: normalizeText(exportMetadata.fitDescription, defaultExportMetadata.fitDescription, 180),
        repositoryUrl: normalizeText(exportMetadata.repositoryUrl, defaultExportMetadata.repositoryUrl, 120)
    };
}

function clamp(value, min, max, fallback) {
    const parsed = Number(value);

    if (Number.isNaN(parsed)) {
        return fallback;
    }

    return Math.min(max, Math.max(min, parsed));
}

function normalizeText(value, fallback, maxLength) {
    const text = String(value ?? "").trim();
    return (text || fallback).slice(0, maxLength);
}

function extractErrorMessage(error) {
    if (error?.cause?.cause?.message) {
        return error.cause.cause.message;
    }

    if (error?.cause?.message) {
        return error.cause.message;
    }

    if (error?.message) {
        return error.message;
    }

    return "未知错误";
}

function buildPipData(state) {
    const lastRecord = state.session?.records.at(-1);
    const summary = state.session?.summary;
    const liveHeartRate = state.ble.heartRate.value;
    const livePower = state.ble.powerMeter.power;
    const liveAveragePower = state.ble.powerMeter.averagePower;

    return {
        hr: liveHeartRate !== null ? String(liveHeartRate) : (lastRecord ? String(lastRecord.heartRate) : "--"),
        power: livePower !== null ? String(livePower) : (lastRecord ? String(lastRecord.power) : "--"),
        time: summary ? formatDuration(summary.elapsedSeconds) : "00:00",
        np: liveAveragePower !== null
            ? String(liveAveragePower)
            : (summary ? String(Math.round(state.settings.power)) : "--")
    };
}

function createInitialBleState() {
    const bluetoothSupported = Boolean(navigator.bluetooth);

    return {
        supported: bluetoothSupported,
        heartRate: {
            isConnecting: false,
            isConnected: false,
            statusLabel: bluetoothSupported ? "未连接" : "不支持",
            deviceName: bluetoothSupported ? "等待连接" : "当前浏览器不支持 Web Bluetooth",
            value: null,
            lastUpdated: null
        },
        powerMeter: {
            isConnecting: false,
            isConnected: false,
            statusLabel: bluetoothSupported ? "未连接" : "不支持",
            deviceName: bluetoothSupported ? "等待连接" : "当前浏览器不支持 Web Bluetooth",
            power: null,
            cadence: null,
            averagePower: null,
            sampleCount: 0,
            powerTotal: 0,
            lastUpdated: null
        }
    };
}

function mapStatusLabel(type) {
    if (type === "connected") {
        return "已连接";
    }

    if (type === "connecting") {
        return "连接中";
    }

    return "未连接";
}
